# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - weewrwe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fabriccio.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fb9e6a065575473d8a7d3d096a71cc5c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fa9d8e24ba9a40a8abbcc9c32a116d73 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fabriccio.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fb9e6a065575473d8a7d3d096a71cc5c }}/sdfrw23:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'weewrwe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_718d158470f540708be1cf1d61a36476 }}
        images: 'fabriccio.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fb9e6a065575473d8a7d3d096a71cc5c }}/sdfrw23:${{ github.sha }}'